Repository zipdabang/Server, pull requests merged in 2023-07, with the labels that each got.

#2 issue/1 : CI : ci/cd 파이프라인 형성
  .github/workflows/deploy.yml
  .platform/nginx.conf
  build.gradle
Labels: enhancement

#3 issue/1 : CI : deploy.yml 수정
  build.gradle
Labels: bug

#12 refactor ♻️ 🐛 issue/7 수정 후 재 배포
  build.gradle
  src/main/java/zipdabang/server/domain/Comments.java
  src/main/java/zipdabang/server/domain/Events.java
  src/main/java/zipdabang/server/domain/FAQ.java
  src/main/java/zipdabang/server/domain/InfoAgree.java
  src/main/java/zipdabang/server/domain/Ingredients.java
  src/main/java/zipdabang/server/domain/Likes.java
  src/main/java/zipdabang/server/domain/Notifications.java
  src/main/java/zipdabang/server/domain/QuestionCategories.java
  src/main/java/zipdabang/server/domain/Questions.java
  src/main/java/zipdabang/server/domain/ReceiveInfo.java
  src/main/java/zipdabang/server/domain/Recipes.java
  src/main/java/zipdabang/server/domain/Replies.java
  src/main/java/zipdabang/server/domain/Scraps.java
  src/main/java/zipdabang/server/domain/Steps.java
  src/main/java/zipdabang/server/domain/Users.java
  src/main/java/zipdabang/server/domain/WeekBestRecipes.java
  src/main/java/zipdabang/server/domain/enums/GenderType.java
  src/main/java/zipdabang/server/domain/enums/StatusType.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: bug, refactor

#9 market관련 entity 작성
  src/main/java/zipdabang/server/domain/Carts.java
  src/main/java/zipdabang/server/domain/Categories.java
  src/main/java/zipdabang/server/domain/KitCategories.java
  src/main/java/zipdabang/server/domain/Products.java
  src/main/java/zipdabang/server/domain/Tags.java
  src/main/java/zipdabang/server/domain/common/BaseEntity.java
  src/main/java/zipdabang/server/domain/enums/OrderStates.java
  src/main/java/zipdabang/server/domain/mapping/Coupons.java
  src/main/java/zipdabang/server/domain/mapping/CreatableRecipes.java
  src/main/java/zipdabang/server/domain/mapping/OrderProductLists.java
  src/main/java/zipdabang/server/domain/mapping/Orders.java
  src/main/java/zipdabang/server/domain/mapping/ProductReviews.java
  src/main/java/zipdabang/server/domain/mapping/ProductTags.java
  src/main/java/zipdabang/server/domain/mapping/RecentWeekViewProducts.java
  src/main/java/zipdabang/server/domain/mapping/RecommendProducts.java
Labels: enhancement

#15 Issue/14 📝 README에 commit convention 작성
  README.MD
Labels: documentation

#18 Issue/13
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/ResponseDto.java
  src/main/java/zipdabang/server/base/exception/ExceptionHandler.java
  src/main/java/zipdabang/server/base/exception/GeneralException.java
  src/main/java/zipdabang/server/base/exception/common/ApiErrorResult.java
  src/main/java/zipdabang/server/domain/Comments.java
  src/main/java/zipdabang/server/domain/Events.java
  src/main/java/zipdabang/server/domain/FAQ.java
  src/main/java/zipdabang/server/domain/InfoAgree.java
  src/main/java/zipdabang/server/domain/Ingredients.java
  src/main/java/zipdabang/server/domain/Likes.java
  src/main/java/zipdabang/server/domain/Notifications.java
  src/main/java/zipdabang/server/domain/QuestionCategories.java
  src/main/java/zipdabang/server/domain/Questions.java
  src/main/java/zipdabang/server/domain/ReceiveInfo.java
  src/main/java/zipdabang/server/domain/Recipes.java
  src/main/java/zipdabang/server/domain/Replies.java
  src/main/java/zipdabang/server/domain/Scraps.java
  src/main/java/zipdabang/server/domain/Steps.java
  src/main/java/zipdabang/server/domain/Users.java
  src/main/java/zipdabang/server/domain/WeekBestRecipes.java
Labels: enhancement

#21 issue/20 🐛 conflict 해결 후 버그 수정
  src/main/java/zipdabang/server/domain/InfoAgree.java
  src/main/java/zipdabang/server/domain/QuestionCategories.java
  src/main/java/zipdabang/server/domain/Recipes.java
  src/main/java/zipdabang/server/domain/Replies.java
Labels: bug, refactor

#23 issue/22 ✨ user api&dto 4개 추가, user domain에 birth column 추가/ ➕ @NotBlank 적용 위해 gradle 의존성 추가
  build.gradle
  src/main/java/zipdabang/server/converter/SmsConverter.java
  src/main/java/zipdabang/server/converter/UserConverter.java
  src/main/java/zipdabang/server/converter/common/BaseConverter.java
  src/main/java/zipdabang/server/domain/Users.java
  src/main/java/zipdabang/server/sms/dto/SmsResponseDto.java
  src/main/java/zipdabang/server/utils/OAuthResult.java
  src/main/java/zipdabang/server/web/controller/UserRestController.java
  src/main/java/zipdabang/server/web/dto/common/BaseDto.java
  src/main/java/zipdabang/server/web/dto/requestDto/UserRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/UserResponseDto.java
Labels: documentation, enhancement

#25 issue/24 ✨ : user logout,quit,store API/DTO 추가
  src/main/java/zipdabang/server/converter/UserConverter.java
  src/main/java/zipdabang/server/web/controller/UserRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/UserRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/UserResponseDto.java
Labels: enhancement

#30 Issue/29 🐛 issue/26 머지 후 충돌, 오류 해결
  src/main/java/zipdabang/server/converter/UserConverter.java
  src/main/java/zipdabang/server/web/controller/UserRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/UserRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/UserResponseDto.java
Labels: bug

#34 Feature/32 Feature/32 🔨 레시피 API & 댓글 API Dto, Converter, Controller 시그니처 작성, 📝 Swagger 세팅 ✨ Spring Security 세팅
  build.gradle
  src/main/java/zipdabang/server/auth/config/JwtSecurityConfig.java
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/auth/filter/JwtRequestFilter.java
  src/main/java/zipdabang/server/auth/handler/JwtAccessDeniedHandler.java
  src/main/java/zipdabang/server/auth/handler/JwtAuthenticationEntryPoint.java
  src/main/java/zipdabang/server/auth/handler/JwtAuthenticationExceptionHandler.java
  src/main/java/zipdabang/server/auth/handler/annotation/AuthUser.java
  src/main/java/zipdabang/server/auth/handler/annotation/AuthUserArgumentResolver.java
  src/main/java/zipdabang/server/auth/provider/TokenProvider.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/exception/handler/JwtAuthenticationException.java
  src/main/java/zipdabang/server/base/exception/handler/UserException.java
  src/main/java/zipdabang/server/config/CorsProperties.java
  src/main/java/zipdabang/server/config/SwaggerConfig.java
  src/main/java/zipdabang/server/config/WebConfig.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/converter/UserConverter.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/repository/userRepositories/UsersRepository.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/controller/UserRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RecipeRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
  src/main/resources/application.yml
Labels: documentation, enhancement, refactor

#38 feature/37 ✨ [FEAT] 카카오 소셜로그인 API v1 추가
  build.gradle
  src/main/java/zipdabang/server/FeignClient/KakaoFeignConfiguration.java
  src/main/java/zipdabang/server/FeignClient/KakaoInfoFeignClient.java
  src/main/java/zipdabang/server/FeignClient/converter/KakaoOAuthConverter.java
  src/main/java/zipdabang/server/FeignClient/dto/KakaoSocialKakaoAccountDto.java
  src/main/java/zipdabang/server/FeignClient/dto/KakaoSocialPartnerDto.java
  src/main/java/zipdabang/server/FeignClient/dto/KakaoSocialProfileDto.java
  src/main/java/zipdabang/server/FeignClient/dto/KakaoSocialUserDto.java
  src/main/java/zipdabang/server/FeignClient/dto/OAuthInfoDto.java
  src/main/java/zipdabang/server/FeignClient/exception/FeignClientExceptionErrorDecoder.java
  src/main/java/zipdabang/server/FeignClient/service/KakaoOauthService.java
  src/main/java/zipdabang/server/FeignClient/service/serviceImpl/KakoOauthServiceImpl.java
  src/main/java/zipdabang/server/ZipdabangServerApplication.java
  src/main/java/zipdabang/server/auth/provider/TokenProvider.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/exception/ExceptionHandler.java
  src/main/java/zipdabang/server/base/exception/handler/CustomFeignClientException.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/enums/SocialType.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/MemberRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: enhancement
