Repository zipdabang/Server, pull requests merged in 2023-10, with the labels that each got.

#150 issue/147 ✨ [FEAT] 팔로우 팔로잉 API 작업
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/Follow.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/FollowRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/ExistMember.java
  src/main/java/zipdabang/server/validation/validator/ExistMemberRequestBodyValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#151 Feature/140 Conflict Resolve
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/resources/application.yml
Labels: :bug: bug

#154 Feature/147 ♻️ [REFACTOR] 팔로우 팔로잉 API 수정
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/Follow.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/FollowRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#156 🔨 Feat : 내가 이 사람을 팔로우하는가? 여부를 리턴하는 매소드 구현
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
Labels: :sparkles: feature

#158 Feature/153 ✨내집다방 화면 조회, 한줄 소개 변경, 기본 프로필로 변경 API 구현
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/FollowRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :sparkles: feature

#165 Feature/157 🐛 redis 연결정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#167 Feature/160 ✨ ♻️ 레시피 관련 수정 요구사항 반영
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/apiPayload/code/RecipeStatus.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/domain/recipe/TempRecipe.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/WeeklyBestRecipeRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/validation/validator/ExistRecipeCategoryValidator.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature, :recycle: refactor

#170 Feature/169 ✨ 임시저장 api 구현 완료(임시저장 목록 제외)
  src/main/java/zipdabang/server/apiPayload/code/RecipeStatus.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/TempRecipe.java
  src/main/java/zipdabang/server/repository/recipeRepositories/TempIngredientRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/TempStepRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RecipeRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature

#171 Wkzb 398 ✨ 🐛 내가 좋아요/스크랩한 레시피 조회, 차단 유저 목록 조회 API 에러 수정
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/repository/memberRepositories/BlockedMemberRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/LikesRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/ScrapRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
Labels: :bug: bug, :sparkles: feature

#173 issue/172 🐛 Fix : API 응답 이상 수정
  src/main/java/zipdabang/server/apiPayload/reponse/ResponseDto.java
  src/main/resources/application.yml
Labels: :bug: bug

#175 Feature/174 🐛 레시피 api 관련 버그 수정
  src/main/java/zipdabang/server/apiPayload/code/RecipeStatus.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
Labels: :bug: bug

#177 Feature/176 ✨ 임시저장 목록 조회, 레시피 수정 api
  src/main/java/zipdabang/server/apiPayload/code/RecipeStatus.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/domain/recipe/Step.java
  src/main/java/zipdabang/server/repository/recipeRepositories/IngredientRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeCategoryMappingRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeCategoryRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/StepRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RecipeRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature

#179 📝 [Docs] : swagger api 응답 표기 수정
  src/main/java/zipdabang/server/apiPayload/reponse/ResponseDto.java
Labels: :memo: documentation

#182 issue/178 ✨ [FEAT] 알림 모아보기 API 추가
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/enums/AlarmType.java
  src/main/java/zipdabang/server/domain/inform/AlarmCategory.java
  src/main/java/zipdabang/server/domain/inform/PushAlarm.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/firebase/fcm/dto/FcmAOSMessage.java
  src/main/java/zipdabang/server/firebase/fcm/service/FirebaseServiceImpl.java
  src/main/java/zipdabang/server/repository/AlarmRepository/AlarmCategoryRepository.java
  src/main/java/zipdabang/server/repository/AlarmRepository/PushAlarmRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#190 issue/189 ♻️ Refactor : 소셜로그인 최종완료 API 수정
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/FcmToken.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#192 💚 Ci : 개발 인프라 이전 및 application.yml profile 분리
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci

#193 Feature/188 ✨ 댓글 알람, 내 레시피 목록 api
  src/main/java/zipdabang/server/domain/enums/AlarmType.java
  src/main/java/zipdabang/server/repository/AlarmRepository/PushAlarmRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#194 Wkzb 406 ✨유저 닉네임으로 검색(전체 유저, 팔로우/팔로잉 중에서) API 구현
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/repository/memberRepositories/MemberRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :sparkles: feature

#195 Wkzb 434 🐛 FIX : 레디스 연결정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#196 issue/187 ✨ [FEAT] 내 문의 상세조회 API 구현
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/apiPayload/code/RecipeStatus.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/repository/memberRepositories/InqueryRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/ExistInquery.java
  src/main/java/zipdabang/server/validation/validator/ExistInqueryValidator.java
  src/main/java/zipdabang/server/validation/validator/ExistRecipeCategoryValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :sparkles: feature

#198 issue/197 ✨ [FEAT] 푸쉬알림 읽음처리 API 구현
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/converter/RootConverter.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/ExistPushAlarm.java
  src/main/java/zipdabang/server/validation/validator/ExistPushAlarmValidator.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RootResponseDto.java
Labels: :sparkles: feature

#206 issue/205 📝 Docs : README 꾸미기 2023/10/17
  README.MD
Labels: :memo: documentation, :tada: setup

#208 Issue/205 README.MD 인물사진 수정
  README.MD
Labels: :memo: documentation

#209 Wkzb 58 READ.ME 수정
  README.MD
Labels: :memo: documentation

#211 issue/210 🐛 [Fix] : 레시피 목록조회 버그 수정
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :bug: bug

#216 Bug/210
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
Labels: :memo: documentation

#217 feature/168 ✨ ♻️ follow순 조회 구현 완료 및 querydsl repository 분리
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/domain/recipe/MemberViewMethod.java
  src/main/java/zipdabang/server/repository/recipeRepositories/MemberViewMethodRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryCustom/CommentRepositoryCustom.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryCustom/RecipeRepositoryCustom.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryCustom/TempRecipeRepositoryCustom.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryImpl/CommentRepositoryImpl.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryImpl/RecipeRepositoryImpl.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryImpl/TempRecipeRepositoryImpl.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
Labels: :sparkles: feature, :recycle: refactor

#219 issue/218 🐛 [BUG] 레시피 관련 버그 수정
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/domain/recipe/MemberViewMethod.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/resources/application.yml
Labels: :bug: bug

#221 Bug/218
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
Labels: :bug: bug

#222 ✨ 비속어 엑셀 파싱 후 db 저장 API 구현, 닉네임 필터링 기능 구현
  build.gradle
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/domain/enums/WordType.java
  src/main/java/zipdabang/server/domain/etc/BannedWord.java
  src/main/java/zipdabang/server/domain/etc/ReservedWord.java
  src/main/java/zipdabang/server/domain/etc/SlangWord.java
  src/main/java/zipdabang/server/repository/BannedWordRepository.java
  src/main/java/zipdabang/server/repository/ReservedWordRepository.java
  src/main/java/zipdabang/server/repository/SlangWordRepository.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/CheckNickname.java
  src/main/java/zipdabang/server/validation/validator/CheckNicknameValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RootResponseDto.java
Labels: :sparkles: feature

#224 feature/213 🐛 POI 라이브러리 충돌 제거
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RootController.java
Labels: :bug: bug

#227 issue/223 🐛 Fix : 최근 조회방법 저장 로직 삭제
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :bug: bug

#228 Bug/223
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
Labels: :memo: documentation

#230 Feature/229 ✨ 공식/바리스타/일반 레시피 목록 조회
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/domain/recipe/MemberViewMethod.java
  src/main/java/zipdabang/server/repository/recipeRepositories/MemberViewMethodRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryCustom/RecipeRepositoryCustom.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryImpl/RecipeRepositoryImpl.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
Labels: :sparkles: feature

#232 Feature/231 ♻️ recipe converter에서 repository 의존성 제거
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :recycle: refactor

#234 ✨ ♻️ feature/233 recipe 목록조회 count api 추가, 카테고리별 top5 isBlocked, ownerId 추가
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/repository/recipeRepositories/recipeRepositoryImpl/RecipeRepositoryImpl.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature, :recycle: refactor

#236 Wkzb-437-feature/235 ✨ ♻️ 주간 베스트 레시피 batch 세팅, 댓글 개수에 차단유저 반영
  build.gradle
  src/main/java/zipdabang/server/ZipdabangServerApplication.java
  src/main/java/zipdabang/server/batch/config/WeeklyBestRecipeBatchConfig.java
  src/main/java/zipdabang/server/batch/schedular/BatchScheduler.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/WeeklyBestRecipe.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor

#239 Feature/238 ♻️ 베스트 레시피 시간 재셋팅, 삭제 허용
  build.gradle
  src/main/java/zipdabang/server/batch/config/WeeklyBestRecipeBatchConfig.java
  src/main/java/zipdabang/server/batch/schedular/BatchScheduler.java
  src/main/java/zipdabang/server/repository/recipeRepositories/WeeklyBestRecipeRepository.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :recycle: refactor

#240 Wkzb 407 feature/237 ✨♻️ 탈퇴 및 중복 관련 예외 처리 추가 및 탈퇴 시 저장하는 정보 추가
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/Deregister.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/redis/service/RedisService.java
  src/main/java/zipdabang/server/redis/service/RedisServiceImpl.java
  src/main/java/zipdabang/server/repository/memberRepositories/DeregisterRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/MemberRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :sparkles: feature, :recycle: refactor

#241 Wkzb 407 feature/237 ♻️ 회원가입 시 입력 정보에 대한 정규표현식 보완
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :recycle: refactor

#243 Bug/242 🐛 레시피에서 s3 객체 삭제는 모든 db 로직이 끝난 후 마지막으로 함.
  src/main/java/zipdabang/server/aws/s3/AmazonS3Manager.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/domain/recipe/WeeklyBestRecipe.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :bug: bug

#245 Feature/244 ✨ 홈배너 api 추가
  src/main/java/zipdabang/server/converter/RootConverter.java
  src/main/java/zipdabang/server/domain/inform/HomeBanner.java
  src/main/java/zipdabang/server/repository/recipeRepositories/HomeBannerRepository.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RootController.java
Labels: :sparkles: feature

#246 Wkzb 407 feature/237 🐛 닉네임 중복검사API에 비속어 필터링 추가
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
Labels: :bug: bug

#247 Wkzb 407 feature/237 📝 스웨거 API 응답 명세 추가
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
Labels: :memo: documentation

#249 Bug/248 🐛 레시피 수정, 임시저장 수정 에러 해결
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :bug: bug

#251 Bug/250 🐛 recipe에서 push alarm delete cascade 되도록
  src/main/java/zipdabang/server/domain/inform/PushAlarm.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
Labels: :bug: bug

#254 :sparkles: Feat : 사용자 신고 API 구현
  src/main/java/zipdabang/server/apiPayload/code/CommonStatus.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/MemberReport.java
  src/main/java/zipdabang/server/repository/memberRepositories/MemberReportRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/CheckSelfTarget.java
  src/main/java/zipdabang/server/validation/validator/CheckSelfValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :sparkles: feature

#255 issue/252 👷 Ci : 릴리즈 인프라 구축
  .ebextensions-release/00-makeFiles.config
  .ebextensions-release/01-set-timezone.config
  .github/workflows/release_deploy.yml
  src/main/resources/application.yml
Labels: :construction_worker: ci

#257 Ci/252 relase db 수정
  src/main/resources/application.yml
Labels: :construction_worker: ci

#258 release db 수정
  src/main/resources/application.yml
Labels: :construction_worker: ci

#259 relase redis 수정
  src/main/resources/application.yml
Labels: :construction_worker: ci

#260 🐛 redis 연결정보 수정
  src/main/resources/application.yml
Labels: :bug: bug

#261 Ci/252
  src/main/resources/application.yml
Labels: :construction_worker: ci

#263 Ci/252 로깅 추가
  src/main/java/zipdabang/server/domain/member/Terms.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeCategoryRepository.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/resources/application.yml
Labels: :bug: bug

#264 로깅 추가
  src/main/java/zipdabang/server/domain/member/Terms.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeCategoryRepository.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/resources/application.yml
Labels: :bug: bug
