Repository zipdabang/Server, pull requests merged in 2023-09, with the labels that each got.

#89 Feature/87 ♻️ ✨ recipe category 테이블/응답 변경, category별 레시피 목록 조회
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/domain/recipe/RecipeCategory.java
  src/main/java/zipdabang/server/domain/recipe/RecipeCategoryMapping.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeCategoryMappingRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeCategoryRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature, :recycle: refactor

#92 Feature/91 ♻️ 🐛 회원가입 시, 주소 직접 입력 삭제, birth값이 Null로 저장되던 에러 해결
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :bug: bug, :recycle: refactor

#96 issue/94 ✨ [FEAT] 나중에 로그인하기 API
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/auth/handler/annotation/Resolver/AuthMemberArgumentResolver.java
  src/main/java/zipdabang/server/auth/provider/TokenProvider.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/exception/ExceptionHandler.java
  src/main/java/zipdabang/server/config/WebConfig.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/redis/service/RedisServiceImpl.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/CheckTempMember.java
  src/main/java/zipdabang/server/validation/validator/CheckTempMemberValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :sparkles: feature

#97 :sparkles: 회원 정보 조회 API 개발
  build.gradle
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :sparkles: feature

#99 Feature/94 temp git action
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/resources/application.yml
Labels: wontfix

#100 Feature/95 🐛 [FIX] 스웨거 오류로 인한 DTO명 변경
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: :bug: bug

#101 issue/93 ✨ [FEAT] 자동로그인 API
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/exception/handler/RootException.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#103 Feature/95 🐛 Conflict Resolve
  src/main/resources/application.yml
Labels: :bug: bug

#105 Feature/98 ♻️ ✨ 레시피 검색 로직 변경된 것 적용
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
Labels: :sparkles: feature, :recycle: refactor

#108 :recycle: Feature/107 레시피 검색 미리보기 로직 변경 적용
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :recycle: refactor

#113 ✨ ♻️ Feature/111 댓글 추가 및 조회, 카테고리 조회 로직 수정
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/BlockedComment.java
  src/main/java/zipdabang/server/domain/recipe/BlockedRecipe.java
  src/main/java/zipdabang/server/repository/recipeRepositories/BlockedCommentRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/BlockedRecipeRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/CommentRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RecipeRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature, :recycle: refactor

#114 Feature/112 ✨ [FEAT] 공지 조회 API 추가
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RootConverter.java
  src/main/java/zipdabang/server/repository/NotificationRepository.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/utils/converter/TimeConverter.java
  src/main/java/zipdabang/server/validation/annotation/ExistNotification.java
  src/main/java/zipdabang/server/validation/validator/ExistNotificationValidator.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RootResponseDto.java
Labels: :sparkles: feature

#116 Feature/115 ✨ 댓글 삭제, 수정 api 완성
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/Comment.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RecipeRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature

#118 Feature/117 ♻️ recipe 관련 api에 timeconverter 적용, 사진 삭제 시 uuid도 db에서 삭제
  src/main/java/zipdabang/server/aws/s3/AmazonS3Manager.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/repository/UuidRepository.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :recycle: refactor

#120 Feature/119 ✨ 댓글 신고, 차단 api 완성
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/converter/RootConverter.java
  src/main/java/zipdabang/server/domain/Report.java
  src/main/java/zipdabang/server/domain/recipe/ReportedComment.java
  src/main/java/zipdabang/server/domain/recipe/ReportedRecipe.java
  src/main/java/zipdabang/server/repository/ReportRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/BlockedCommentRepository.java
  src/main/java/zipdabang/server/repository/recipeRepositories/ReportedCommentRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RecipeRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RootResponseDto.java
Labels: :sparkles: feature

#122 Feature/91 ✨📝유저 선호 카테고리 조회 API, 회원가입 로직 변경 적용
  src/main/java/zipdabang/server/aws/s3/AmazonS3Manager.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/repository/memberRepositories/PreferCategoryRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :memo: documentation, :sparkles: feature

#123 Feature/91 📝 API 명세 작성
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
Labels: :memo: documentation

#124 Feature/91✨유저 선호 카테고리 수정 API
  src/main/java/zipdabang/server/repository/CategoryRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/PreferCategoryRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :sparkles: feature

#125 Feature/91📝 API 명세 작성
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
Labels: :memo: documentation

#128 🐛 [Fix] 자동로그인, 로그아웃 API 버그 수정
  src/main/java/zipdabang/server/auth/provider/TokenProvider.java
  src/main/java/zipdabang/server/redis/domain/LoginStatus.java
  src/main/java/zipdabang/server/repository/memberRepositories/FcmTokenRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/resources/application.yml
Labels: :bug: bug

#130 Hotfix/127 🐛 [FIX] swagger cors 수정
  src/main/java/zipdabang/server/config/WebConfig.java
Labels: :bug: bug

#133 ♻️ Refactor : api 응답 수정
  src/main/java/zipdabang/server/base/Code.java
Labels: :recycle: refactor

#137 :sparkles: [FEAT]회원탈퇴 API(스프링배치 적용 전)
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/enums/DeregisterType.java
  src/main/java/zipdabang/server/domain/member/Deregister.java
  src/main/java/zipdabang/server/domain/member/DeregisterReason.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/DeregisterReasonRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/DeregisterRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/CheckDeregister.java
  src/main/java/zipdabang/server/validation/validator/CheckDeregisterValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :sparkles: feature

#141 issue/135 ✨ [FEAT] 오류 문의 및 신고하기 API 구현
  src/main/java/zipdabang/server/aws/s3/AmazonS3Manager.java
  src/main/java/zipdabang/server/config/AmazonConfig.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/Inquery.java
  src/main/java/zipdabang/server/domain/member/InqueryImage.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/InqueryImageRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/InqueryRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/utils/converter/TimeConverter.java
  src/main/java/zipdabang/server/validation/annotation/CheckPage.java
  src/main/java/zipdabang/server/validation/validator/CheckPageValidator.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#142 issue/135 ✨ [FEAT] 오류 문의 및 신고하기 API 구현
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :sparkles: feature

#145 issue/143 ✨ Feat : FCM 알림 전송 구현
  build.gradle
  src/main/java/zipdabang/server/FeignClient/Config/FCMFeignConfiguration.java
  src/main/java/zipdabang/server/FeignClient/Config/KakaoFeignConfiguration.java
  src/main/java/zipdabang/server/FeignClient/Config/NaverFeignConfiguration.java
  src/main/java/zipdabang/server/FeignClient/FCMFeignClient.java
  src/main/java/zipdabang/server/FeignClient/KakaoInfoFeignClient.java
  src/main/java/zipdabang/server/FeignClient/NaverSmsFeignClient.java
  src/main/java/zipdabang/server/FeignClient/dto/fcm/FCMResponseDto.java
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/firebase/fcm/dto/FcmAOSMessage.java
  src/main/java/zipdabang/server/firebase/fcm/service/FirebaseService.java
  src/main/java/zipdabang/server/firebase/fcm/service/FirebaseServiceImpl.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/requestDto/RootRequestDto.java
  src/main/resources/application.yml
  src/main/resources/firebase/zipdabang-firebase-key.json
Labels: :sparkles: feature

#146 Feature/140 ✨ [FEAT] 유저 차단 API 구현
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/repository/memberRepositories/BlockedMemberRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :sparkles: feature

#149 Feature/148 ♻️ ✨ 좋아요/스크랩 refactor, 카테고리별 top5 레시피 api
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/validation/annotation/ExistRecipeCategory.java
  src/main/java/zipdabang/server/validation/validator/ExistRecipeCategoryValidator.java
  src/main/java/zipdabang/server/web/controller/RecipeRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature, :recycle: refactor
