Repository zipdabang/Server, pull requests merged in 2023-08, with the labels that each got.

#42 Feature/37 ♻️ 소셜로그인 API 수정
  build.gradle
  src/main/java/zipdabang/server/ZipdabangServerApplication.java
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/domain/market/OrderProduct.java
  src/main/java/zipdabang/server/domain/market/Orders.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/domain/recipe/Likes.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/domain/recipe/WeeklyBestRecipe.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: refactor

#41 Feature/40 ✨ 로그인 추가정보 저장 API
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/InfoAgree.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/CategoryRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/MemberRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/PreferCategoryRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: enhancement

#45 issue/44 :bug: Feature/40 merge 버그 수정
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
Labels: bug

#51 Feature/50 ➕ ✨ ♻️ 리프레시 토큰을 활용하기 위한 redis 설정 및 refresh 토큰 활용 API 추가, 소셜 로그인 응답 수정
  build.gradle
  src/main/java/zipdabang/server/ZipdabangServerApplication.java
  src/main/java/zipdabang/server/auth/config/JwtSecurityConfig.java
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/auth/filter/JwtRequestFilter.java
  src/main/java/zipdabang/server/auth/provider/TokenProvider.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/exception/handler/RefreshTokenExceptionHandler.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/redis/domain/LoginStatus.java
  src/main/java/zipdabang/server/redis/domain/RefreshToken.java
  src/main/java/zipdabang/server/redis/repository/LoginStatusRepository.java
  src/main/java/zipdabang/server/redis/repository/RefreshTokenRepository.java
  src/main/java/zipdabang/server/redis/service/RedisService.java
  src/main/java/zipdabang/server/redis/service/RedisServiceImpl.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/utils/dto/OAuthJoin.java
  src/main/java/zipdabang/server/utils/dto/OAuthResult.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#54 Feature/50 2023.8.17 api 수정
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
Labels: :memo: documentation, :recycle: refactor

#55 Feature/52 ✨ [FEAT] 마켓1, 마켓2, 장비1에 필요한 API
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/market/ProductConverter.java
  src/main/java/zipdabang/server/domain/market/MarketCategory.java
  src/main/java/zipdabang/server/web/controller/MarketController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MarketResponseDto.java
  src/main/resources/application.yml
Labels: :memo: documentation, :sparkles: feature

#56 Feature/52 🐛 최근 조회 아이템 목록 converter 수정
  src/main/java/zipdabang/server/converter/market/ProductConverter.java
Labels: :bug: bug

#58 Feature/57 ✨ [FEAT] 음료 카테고리 조회 API, 이용약관 조회 API
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/converter/RootConverter.java
  src/main/java/zipdabang/server/domain/Category.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/domain/member/Terms.java
  src/main/java/zipdabang/server/domain/member/TermsAgree.java
  src/main/java/zipdabang/server/repository/TermsAgreeRepository.java
  src/main/java/zipdabang/server/repository/TermsRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/RootService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/service/serviceImpl/RootServiceImpl.java
  src/main/java/zipdabang/server/utils/dto/OAuthJoin.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
  src/main/java/zipdabang/server/web/dto/responseDto/RootResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature, :recycle: refactor

#60 Feature/57 ♻️ Refactor : 약관 동의 조회 API 수정, 📝 Docs : API 명세서 추가작성
  src/main/java/zipdabang/server/converter/MemberConverter.java
  src/main/java/zipdabang/server/domain/member/Terms.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/responseDto/MemberResponseDto.java
Labels: :memo: documentation, :recycle: refactor

#63 issue/62 :memo: Docs : 닉네임 중복검사 API 명세서 작성
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
Labels: :memo: documentation

#49 [Feature/48] 🔧 01-set-timezone.config 추가
  .ebextensions/01-set-timezone.config
Labels: :bug: bug, :memo: documentation

#65 Issue/64 ♻️ [REFACTOR] 소셜로그인 API수정, 로그아웃 API 수정
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/domain/member/FcmToken.java
  src/main/java/zipdabang/server/domain/member/Member.java
  src/main/java/zipdabang/server/repository/memberRepositories/FcmTokenRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/dto/requestDto/MemberRequestDto.java
  src/main/resources/application.yml
Labels: :recycle: refactor

#68 issue/67 ✨ [FEAT] S3 설정
  build.gradle
  src/main/java/zipdabang/server/aws/s3/AmazonS3Manager.java
  src/main/java/zipdabang/server/config/AmazonConfig.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#72 ✨ Feature/71 banner img 불러오는 api swagger 추가
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RootResponseDto.java
Labels: :sparkles: feature

#76 📝[FIX] Beanstalk 배포 설정 변경
  .github/workflows/deploy.yml
Labels: :memo: documentation

#74 ✨[FEAT] SMS 인증 API 개발
  src/main/java/zipdabang/server/FeignClient/KakaoFeignConfiguration.java
  src/main/java/zipdabang/server/FeignClient/NaverFeignConfiguration.java
  src/main/java/zipdabang/server/FeignClient/NaverSmsFeignClient.java
  src/main/java/zipdabang/server/FeignClient/exception/FeignClientExceptionErrorDecoder.java
  src/main/java/zipdabang/server/auth/config/SecurityConfig.java
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/base/exception/handler/AuthNumberException.java
  src/main/java/zipdabang/server/domain/etc/AuthNumber.java
  src/main/java/zipdabang/server/repository/AuthNumberRepository.java
  src/main/java/zipdabang/server/repository/memberRepositories/MemberRepository.java
  src/main/java/zipdabang/server/service/MemberService.java
  src/main/java/zipdabang/server/service/serviceImpl/MemberServiceImpl.java
  src/main/java/zipdabang/server/sms/dto/MessageDto.java
  src/main/java/zipdabang/server/sms/dto/PhoneAuthDto.java
  src/main/java/zipdabang/server/sms/dto/SmsRequestDto.java
  src/main/java/zipdabang/server/sms/service/SmsService.java
  src/main/java/zipdabang/server/sms/service/serviceImpl/SmsServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#77 Feature/73 ✨ 레시피 검색, [피그마 레시피1] 유저 타입별 미리보기 완성
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/repository/recipeRepositories/RecipeRepository.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#79 Feature/78 🐛 merge 충돌 해결
  src/main/resources/application.yml
Labels: :bug: bug

#80 Feature/69 🎨 Sms API 응답 형식 통일
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/sms/service/SmsService.java
  src/main/java/zipdabang/server/sms/service/serviceImpl/SmsServiceImpl.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/resources/application.yml
Labels: :memo: documentation

#83 Feature/81 ♻️ 📝 에러 코드 변경 및 재배치
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/web/controller/MarketController.java
  src/main/java/zipdabang/server/web/controller/MemberRestController.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/resources/application.yml
Labels: :memo: documentation, :recycle: refactor

#84 Feature/82 ✨ 레시피 배너 api 추가, paging index 및 상세 레시피 응답 변경
  src/main/java/zipdabang/server/base/Code.java
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
  src/main/java/zipdabang/server/web/controller/RootController.java
  src/main/java/zipdabang/server/web/dto/responseDto/RecipeResponseDto.java
Labels: :sparkles: feature

#86 Feature/85 ✨ 레시피 스크랩, 좋아요 완성
  src/main/java/zipdabang/server/converter/RecipeConverter.java
  src/main/java/zipdabang/server/domain/recipe/Likes.java
  src/main/java/zipdabang/server/domain/recipe/Recipe.java
  src/main/java/zipdabang/server/domain/recipe/Scrap.java
  src/main/java/zipdabang/server/service/RecipeService.java
  src/main/java/zipdabang/server/service/serviceImpl/RecipeServiceImpl.java
  src/main/java/zipdabang/server/web/controller/RecipeController.java
Labels: :sparkles: feature
